"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/layout";
import MenuContextProvider from "@/context/MenuContext";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "D5 PlayStation",
//   description: "Generated by create next app",
// };

// halaman yang mau saya disable dari navbar
const disableLayoutDashboard = ["/login", "/register"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableLayoutDashboard.includes(pathname) && (
          <Layout>{children}</Layout>
        )}

        {disableLayoutDashboard.includes(pathname) && children}

        {/* <MenuContextProvider> */}
        {/* <Layout>{children}</Layout> */}
        {/* </MenuContextProvider> */}
      </body>
    </html>
  );
}
